export { default as DisplayBatchData } from './Render Components/DisplayBatchData.jsx'
export { default as DisplayProductData } from './Render Components/DisplayProductData.jsx'
export { default as DisplayTransactionData } from './Render Components/DisplayTransactionData.jsx'
export { default as BatchRegistrationInteraction } from './Page Components/BatchRegistrationInteraction.jsx'
export { default as ProductRegistrationInteraction } from './Page Components/ProductRegistrationInteraction.jsx'
export { default as TransactionRegistration } from './Page Components/TransactionRegistration.jsx'
export {default as TraceProducts} from './Render Components/TraceProducts.jsx'
// some weird way of exporting jsx code, i fuckin hate this 
export {default as Buttons} from './Buttons/Button.jsx'
export {default as CustomTexts} from './CustomTexts/TextFade.jsx'
export {default as Footer} from './Footer/Footer.jsx'
export {default as NavItems} from './Navbar/NavItems.jsx'
export {default as SideNav} from './Navbar/SideNav.jsx'
export {default as CallToActionSection} from './Others/CallToActionSection.jsx'
export {default as CollectionTile} from './Tiles/CollectionTile.jsx'
export {default as GalleryTile} from './Tiles/GalleryTile.jsx'
export {default as HeroServiceItem} from './Tiles/HeroServiceItem.jsx'
export {default as TestimonialUserTile} from './Tiles/TestimonialUserTile.jsx'
export {default as WhatsNewItem} from './Tiles/WhatsNewItem.jsx'
export {default as WhatsNewModal} from './Tiles/WhatsNewModal.jsx'
export {default as WhyChooseUsEstateTile} from './Tiles/WhyChooseUsEstateTile.jsx'
export {default as CustomAvatar} from '../Reusables/CustomAvatar.jsx'
